# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `rqrcode` gem.
# Please instead update this file by running `bin/tapioca gem rqrcode`.

module RQRCode; end
module RQRCode::Export; end

module RQRCode::Export::ANSI
  # Returns a string of the QR code as
  # characters writen with ANSI background set.
  #
  # Options:
  # light: Foreground ("\033[47m")
  # dark: Background ANSI code. ("\033[40m")
  # fill_character: The written character. ('  ')
  # quiet_zone_size: (4)
  def as_ansi(options = T.unsafe(nil)); end
end

module RQRCode::Export::HTML
  # Use this module to HTML-ify the QR code if you just want the default HTML
  def as_html; end

  private

  def rows; end
end

class RQRCode::Export::HTML::Cell < ::Struct
  def as_html; end
  def html_class; end
end

class RQRCode::Export::HTML::Row < ::Struct
  def as_html; end
  def cells; end
end

class RQRCode::Export::HTML::Rows < ::Struct
  def as_html; end
  def rows; end
end

module RQRCode::Export::PNG
  # Render the PNG from the QR Code.
  #
  # Options:
  # fill  - Background ChunkyPNG::Color, defaults to 'white'
  # color - Foreground ChunkyPNG::Color, defaults to 'black'
  #
  # When option :file is supplied you can use the following ChunkyPNG constraints
  # color_mode  - The color mode to use. Use one of the ChunkyPNG::COLOR_* constants.
  #               (defaults to 'ChunkyPNG::COLOR_GRAYSCALE')
  # bit_depth   - The bit depth to use. This option is only used for indexed images.
  #               (defaults to 1 bit)
  # interlace   - Whether to use interlacing (true or false).
  #               (defaults to ChunkyPNG default)
  # compression - The compression level for Zlib. This can be a value between 0 and 9, or a
  #               Zlib constant like Zlib::BEST_COMPRESSION
  #               (defaults to ChunkyPNG default)
  #
  # There are two sizing algorithms.
  #
  # - Original that can result in blurry and hard to scan images
  # - Google's Chart API inspired sizing that resizes the module size to fit within the given image size.
  #
  # The Googleis one will be used when no options are given or when the new size option is used.
  #
  # *Google*
  # size            - Total size of PNG in pixels. The module size is calculated so it fits.
  #                   (defaults to 120)
  # border_modules  - Width of white border around in modules.
  #                   (defaults to 4).
  #
  #  -- DONT USE border_modules OPTION UNLESS YOU KNOW ABOUT THE QUIET ZONE NEEDS OF QR CODES --
  #
  # *Original*
  # module_px_size  - Image size, in pixels.
  # border          - Border thickness, in pixels
  #
  # It first creates an image where 1px = 1 module, then resizes.
  # Defaults to 120x120 pixels, customizable by option.
  def as_png(options = T.unsafe(nil)); end
end

module RQRCode::Export::SVG
  # Render the SVG from the Qrcode.
  #
  # Options:
  # offset          - Padding around the QR Code in pixels
  #                   (default 0)
  # fill            - Background color e.g "ffffff"
  #                   (default none)
  # color           - Foreground color e.g "000"
  #                   (default "000")
  # module_size     - The Pixel size of each module
  #                   (defaults 11)
  # shape_rendering - SVG Attribute: auto | optimizeSpeed | crispEdges | geometricPrecision
  #                   (defaults crispEdges)
  # standalone      - Whether to make this a full SVG file, or only an svg to embed in other svg
  #                   (default true)
  # use_path        - Use <path> to render SVG rather than <rect> to significantly reduce size
  #                   and quality. This will become the default in future versions.
  #                   (default false)
  # viewbox         - replace `width` and `height` in <svg> with a viewBox, allows CSS scaling
  #                   (default false)
  # svg_attributes  - A optional hash of custom <svg> attributes. Existing attributes will remain.
  #                   (default {})
  def as_svg(options = T.unsafe(nil)); end
end

class RQRCode::Export::SVG::BaseOutputSVG
  # @return [BaseOutputSVG] a new instance of BaseOutputSVG
  def initialize(qrcode); end

  # Returns the value of attribute result.
  def result; end
end

RQRCode::Export::SVG::DEFAULT_SVG_ATTRIBUTES = T.let(T.unsafe(nil), Array)

class RQRCode::Export::SVG::Edge < ::Struct
  def end_x; end
  def end_y; end
end

class RQRCode::Export::SVG::Path < ::RQRCode::Export::SVG::BaseOutputSVG
  def build(module_size, offset, color); end
end

class RQRCode::Export::SVG::Rect < ::RQRCode::Export::SVG::BaseOutputSVG
  def build(module_size, offset, color); end
end

RQRCode::Export::SVG::SVG_PATH_COMMANDS = T.let(T.unsafe(nil), Hash)

class RQRCode::QRCode
  include ::RQRCode::Export::ANSI
  include ::RQRCode::Export::HTML
  include ::RQRCode::Export::PNG
  include ::RQRCode::Export::SVG
  extend ::Forwardable

  # @return [QRCode] a new instance of QRCode
  def initialize(string, *args); end

  def modules(*args, **_arg1, &block); end

  # Returns the value of attribute qrcode.
  def qrcode; end

  def to_s(*args, **_arg1, &block); end
end

RQRCode::VERSION = T.let(T.unsafe(nil), String)
