# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `ClearanceMailer`.
# Please instead update this file by running `bin/tapioca dsl ClearanceMailer`.

class ClearanceMailer
  class << self
    sig { params(user: T.untyped).returns(::ActionMailer::MessageDelivery) }
    def change_password(user); end

    sig { returns(::ActionMailer::MessageDelivery) }
    def roadie_options; end
  end
end
