#!/usr/bin/env ruby

ENV["RAILS_ENV"] ||= "production"
require_relative "../config/environment"

owners = User.joins(rubygems: :gem_download).order("gem_downloads.count DESC").limit(100).uniq

owners.each do |owner|
  next if owner.mfa_required

  owner.update(mfa_required: true) 
  puts "update #{owner.email} to require mfa"
end

