name: Docker
on:
  pull_request:
  push:
    branches:
      - master
permissions:
  contents: read

jobs:
  build:
    name: Docker build (and optional push)
    runs-on: ubuntu-22.04
    env:
      RUBYGEMS_VERSION: 3.4.3
      RUBY_VERSION: 3.2.0
    steps:
    - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@2dd22fa31c04297d369158eb483250f578504a9f # master
    - name: Cache Docker layers
      uses: actions/cache@58c146cc91c5b9e778e71775dfe9bf1442ad9a12 # v3.2.3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-rubygems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-rubygems-org
    - name: Install and start services (needed for image test)
      run: docker-compose up -d
    - name: build, test and optionally push docker image
      run: ./script/build_docker.sh
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    # Temp fix
    # https://github.com/docker/build-push-action/issues/252
    # https://github.com/moby/buildkit/issues/1896
    - name: Move cache
      run: |
        rm -rf /tmp/.buildx-cache
        mv /tmp/.buildx-cache-new /tmp/.buildx-cache
